---
- name: Upload python module
  copy: src=ModifyMXDatasource.py dest=/tmp/ModifyMXDatasource.py
  
- name: configure MX datasource
  alter_datasource:    
    service_name: "{{alter_service_name}}"      
    datasource_name: "{{alter_datasource_name}}"
    max_server: "{{alter_maxserver_count}}"
    idle_server: "{{alter_idleserver_count}}"
    init_server: "{{alter_initserver_count}}"
  register: result
  
- debug: var=result
