---
- name: Upload python module
  copy: src=ConfigureMXDatasource.py dest=/tmp/ConfigureMXDatasource.py
  
- name: configure datasource  
  configure_datasource: 
    service_name: "{{service_name}}"    
    datasource_name: "{{datasource_name}}"    
    max_server: "10"
    idle_server: "5"
    init_server: "5"
    action: "{{datasource_action}}"
  register: result

- debug: var=result 
