---
- name: Upload python module
  copy: src=PersistenceMXService.py dest=/tmp/PersistenceMXService.py
  
- name: configure persistence mx service  
  persistence_mxservice: 
    process_name: "{{process_name}}"
    service_name: "{{persitence_service_name}}"    
    port_number: "{{persitence_service_port}}"
    action: "{{action}}"
  register: result
  
- debug: var=result 
